AV-131: add customs hook
webdev-mistress/avochatF pull request #1
Opened 2021-03-04 17:08 UTC by webdev-mistress

2021-03-04 18:26 UTC, Leyrus requested changes
В общем и целом хорошо, но нужно исправить некоторые недочеты.
Помимо правок было бы хорошо пройтись по всему коду и убрать из него созданные в jsx колбеки в пользу двойных колбеков в коде.
Так же проверить во всем коде наличие useCallback, в некоторых обработчиках он отсутствует.
Так же нужно привести стилистику кода в один вид, но это будет правиться в рамках задачи AV-132 в следующем спринте

2021-03-04 18:26 UTC, Leyrus commented on src/pages/chat/leftChat/components/chats/hook.ts
> +        if (nodeName !== 'path' && nodeName !== 'svg') {
Нужно попробовать решить эту задачку другим путем. Скорее всего тут поможет stopPropagination,тут можно прочитать подробнее - https://ru.reactjs.org/docs/events.html#mouse-events

2021-03-04 18:26 UTC, Leyrus commented on src/pages/chat/leftChat/components/chats/hook.ts
> +        const onCreateChat = ((chatName: string) => {
Функцию onCreateChat лучше создать где-нибудь вне функции onCreateDialog.

2021-03-04 18:26 UTC, Leyrus commented on src/pages/chat/leftChat/components/dialogs/hook.ts
> +export const useDialog = (props: IProps) => {
тут тоже, пропсы не самое лучшее название

2021-03-04 18:26 UTC, Leyrus commented on src/pages/chat/leftChat/components/settingsBlock/hook.ts
> +export const useSettingsBlock = (props: IProps) => {
тут тоже пропсы поменять

2021-03-04 18:26 UTC, Leyrus commented on src/pages/chat/leftChat/components/settingsBlock/hook.ts
> +   }, [dispatch]);
Тут не хватает удаления токена с сервера, нужно будет реализовать чуть позже в рамках задачи AV-133

2021-03-04 18:26 UTC, Leyrus commented on src/pages/chat/mainChat/components/chatMessages/hook.ts
> +export const useChatMessages = (props: IProps) => {
поменять название

2021-03-04 18:26 UTC, Leyrus commented on src/pages/chat/mainChat/components/chatSettings/hook.ts
> +export const useChatSettings = (props: IProps) => {
поменять название

2021-03-04 18:26 UTC, Leyrus commented on src/pages/chat/mainChat/components/chatSettings/hook.ts
> +        ? format(new Date(message.dateChange), 'HH:mm:ss dd.MM.yyyy') : '';
Было бы не плохо вынести эту реализацию в общие хелперы, это с очень высокой вероятностью еще много где пригодится.

2021-03-04 18:26 UTC, Leyrus commented on src/pages/chat/mainChat/components/menuMessage/hook.ts
> +export const useMenuMessage = (props: IProps) => {
изменить название

2021-03-04 18:26 UTC, Leyrus commented on src/pages/chat/mainChat/components/menuMessage/hook.ts
> +       }, 0);
Хорошо было бы разобраться почему этот костыль вбит. Как минимум нужно пометить это с помощью TODO.

2021-03-04 18:26 UTC, Leyrus commented on src/pages/chat/mainChat/components/menuMessage/hook.ts
> +       dispatch(deleteMessage(_.get(state, 'selectedMessage.messageId', 0)));
тут лучше всего убрать get и  сделать проверку, что есть у нас есть state.selectedMessage?.messageId, то вызывать dispatch и удалять. Иначе ловить ошибку.
Если в таком коде как сейчас произойдет ошибка, то ее будет очень не просто отдебажить, по этому лучше об этой ошибке говорить. выводя ее в консоль или кидая через throw.

2021-03-04 18:26 UTC, Leyrus commented on src/pages/chat/mainChat/components/messageContent/hook.ts
> +export const useMessageContent = (props: IProps) => {
поменять название

2021-03-04 18:26 UTC, Leyrus commented on src/pages/chat/mainChat/components/optionIcons.tsx
> +                    onClick={() => onSendEditMessage(message.message)}
лучше не создавать колбеки в jsx.

2021-03-04 18:26 UTC, Leyrus commented on src/pages/chat/mainChat/components/settingsMessage/hook.ts
> +export const useSettingsMessage = (props: IProps) => {
поменять название.

2021-03-06 19:41 UTC, webdev-mistress commented on src/pages/chat/mainChat/components/messageContent/hook.ts
> +export const useMessageContent = (props: IProps) => {
какое именно название нужно поменять?

2021-03-06 19:42 UTC, webdev-mistress commented on src/pages/chat/mainChat/components/settingsMessage/hook.ts
> +export const useSettingsMessage = (props: IProps) => {
какое именно название нужно поменять?

2021-03-06 21:39 UTC, Leyrus approved these changes
В целом хорошо. Еще есть очень много разных проблем, но все они будут решаться в рамках других задач. Эта задача на мой взгляд выполнена успешно)

2021-03-06 21:42 UTC, merged